version: '3.8'
services: 
  playwright-test:
    image: pw-practice 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "9704:9704"
    command:  npm run test:allure
    volumes: 
      - ./playwright-report:/app/playwright-report
      - ./playwright-tests:/app/playwright-tests
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report